In [13]:
import pandas as pd
import matplotlib.pyplot as plt
df= pd.DataFrame({
    "Name": ["Braund, Mr. Owen Harris", "Allen, Mr. William Henry", "Bonnell, Miss.Elizabeth"],
    "Age":[22, 35, 58],
    "Sex": ["male", "male", "female"]
})
df

                       Name  Age     Sex
0   Braund, Mr. Owen Harris   22    male
1  Allen, Mr. William Henry   35    male
2   Bonnell, Miss.Elizabeth   58  female

In [14]:
df['Age']

0    22
1    35
2    58
Name: Age, dtype: int64

In [15]:
AGES= pd.Series([22, 35, 58], name="Age")
AGES

0    22
1    35
2    58
Name: Age, dtype: int64

In [16]:
df['Age'].max()

58

In [18]:
AGES.max()

58

In [19]:
df.describe()

             Age
count   3.000000
mean   38.333333
std    18.230012
min    22.000000
25%    28.500000
50%    35.000000
75%    46.500000
max    58.000000

In [20]:
titanic= pd.read_csv("https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/titanic.csv")
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [21]:
titanic.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [23]:
titanic.to_excel("titanic.xlsx", sheet_name="passengers", index=False)

In [24]:
titanic= pd.read_excel("titanic.xlsx", sheet_name="passengers")
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [25]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [26]:
AGES=titanic["Age"]
AGES.head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: Age, dtype: float64

In [27]:
type(titanic["Age"])

pandas.core.series.Series

In [28]:
titanic["Age"].shape

(891,)

In [29]:
age_sex=titanic[["Age", "Sex"]]
age_sex.head()

    Age     Sex
0  22.0    male
1  38.0  female
2  26.0  female
3  35.0  female
4  35.0    male

In [30]:
titanic[["Age", "Sex"]].shape

(891, 2)

In [31]:
above_35=titanic[titanic["Age"]>35]
above_35.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S

In [32]:
class_23=titanic[titanic["Pclass"].isin([2,3])]
class_23.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
7,8,0,3,"Palsson, Master Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S

In [33]:
class_23=titanic[(titanic["Pclass"]==2) | (titanic["Pclass"]==3)]
class_23.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
7,8,0,3,"Palsson, Master Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S

In [34]:
age_no_na=titanic[titanic["Age"].notna()]
age_no_na.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [36]:
adult_names=titanic.loc[titanic["Age"]>35]
adult_names.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S

In [37]:
adult_names=titanic.loc[titanic["Age"]>35, "Name"]
adult_names.head()

1     Cumings, Mrs. John Bradley (Florence Briggs Th...
6                               McCarthy, Mr. Timothy J
11                              Bonnell, Miss Elizabeth
13                          Andersson, Mr. Anders Johan
15                     Hewlett, Mrs. (Mary D Kingcome)
Name: Name, dtype: object

In [38]:
titanic.iloc[9:25,2:5]

    Pclass                                               Name     Sex
9        2                Nasser, Mrs. Nicholas (Adele Achem)  female
10       3                     Sandstrom, Miss Marguerite Rut  female
11       1                            Bonnell, Miss Elizabeth  female
12       3                     Saundercock, Mr. William Henry    male
13       3                        Andersson, Mr. Anders Johan    male
14       3                Vestrom, Miss Hulda Amanda Adolfina  female
15       2                   Hewlett, Mrs. (Mary D Kingcome)   female
16       3                                Rice, Master Eugene    male
17       2                       Williams, Mr. Charles Eugene    male
18       3  Vander Planke, Mrs. Julius (Emelia Maria Vande...  female
19       3                            Masselmani, Mrs. Fatima  female
20       2                               Fynney, Mr. Joseph J    male
21       2                              Beesley, Mr. Lawrence    male
22       3                         McGowan, Miss Anna "Annie"  female
23       1                       Sloper, Mr. William Thompson    male
24       3                       Palsson, Miss Torborg Danira  female

In [39]:
anon=titanic.iloc[0:3, 3]= "anonymous"
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,anonymous,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,anonymous,female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,anonymous,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [40]:
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,anonymous,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,anonymous,female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,anonymous,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [41]:
titanic ["Age"].mean()

29.69911764705882

In [42]:
titanic[["Age", "Fare"]].median()

Age     28.0000
Fare    14.4542
dtype: float64

In [43]:
titanic[["Age", "Fare"]].describe()

              Age        Fare
count  714.000000  891.000000
mean    29.699118   32.204208
std     14.526497   49.693429
min      0.420000    0.000000
25%     20.125000    7.910400
50%     28.000000   14.454200
75%     38.000000   31.000000
max     80.000000  512.329200

In [46]:
titanic.agg(
    {
        "Age":["min", "max", "median"],
        "Fare":["min", "max", "median", "mean"]
    }
)

          Age        Fare
min      0.42    0.000000
max     80.00  512.329200
median  28.00   14.454200
mean      NaN   32.204208

In [47]:
titanic[["Sex", "Age"]].groupby("Sex").mean()

              Age
Sex
female  27.915709
male    30.726645

In [48]:
titanic[["Sex", "Age"]].groupby("Sex").mean()

              Age
Sex
female  27.915709
male    30.726645

In [49]:
titanic[["Sex", "Age"]].groupby("Sex").max()

         Age
Sex
female  63.0
male    80.0

In [50]:
titanic[["Sex", "Age"]].groupby("Sex").first()

         Age
Sex
female  38.0
male    22.0

In [51]:
titanic.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,anonymous,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,anonymous,female,38.0,1,0,PC 17599,71.2833,C85,C

In [52]:
titanic.groupby("Sex")["Age"].mean()

Sex
female    27.915709
male      30.726645
Name: Age, dtype: float64

In [53]:
titanic.groupby(["Sex", "Pclass"])["Fare"].mean()

Sex     Pclass
female  1         106.125798
        2          21.970121
        3          16.118810
male    1          67.226127
        2          19.741782
        3          12.661633
Name: Fare, dtype: float64

In [54]:
titanic["Pclass"].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [55]:
titanic.groupby("Pclass")["Pclass"].count()

Pclass
1    216
2    184
3    491
Name: Pclass, dtype: int64

In [56]:
titanic.sort_values(by="Age",ascending=False).head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q

In [57]:
titanic.sort_values(by=["Pclass", "Age"], ascending=False).head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
280,281,0,3,"Duane, Mr. Frank",male,65.0,0,0,336439,7.7500,NaN,Q
483,484,1,3,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,NaN,S
326,327,0,3,"Nysveen, Mr. Johan Hansen",male,61.0,0,0,345364,6.2375,NaN,S

In [58]:
titanic.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [59]:
titanic["Name"].str.lower()

0                                         anonymous
1                                         anonymous
2                                         anonymous
3      futrelle, mrs. jacques heath (lily may peel)
4                          allen, mr. william henry
                           ...
886                           montvila, rev. juozas
887                     graham, miss margaret edith
888         johnston, miss catherine helen "carrie"
889                           behr, mr. karl howell
890                             dooley, mr. patrick
Name: Name, Length: 891, dtype: object

In [60]:
titanic["Name"].str.split(",")

0                                          [anonymous]
1                                          [anonymous]
2                                          [anonymous]
3      [Futrelle,  Mrs. Jacques Heath (Lily May Peel)]
4                          [Allen,  Mr. William Henry]
                            ...
886                           [Montvila,  Rev. Juozas]
887                     [Graham,  Miss Margaret Edith]
888         [Johnston,  Miss Catherine Helen "Carrie"]
889                           [Behr,  Mr. Karl Howell]
890                             [Dooley,  Mr. Patrick]
Name: Name, Length: 891, dtype: object

In [62]:
titanic["Surname"]=titanic["Name"].str.split(",").str.get(0)
titanic["Surname"]

0      anonymous
1      anonymous
2      anonymous
3       Futrelle
4          Allen
         ...
886     Montvila
887       Graham
888     Johnston
889         Behr
890       Dooley
Name: Surname, Length: 891, dtype: object

In [63]:
titanic["Name"].str.contains("Countess")

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: Name, Length: 891, dtype: bool

In [64]:
titanic["Name_main"]=titanic['Name'].str.split(",").str.get(1)
titanic['Name_main']

0                                      NaN
1                                      NaN
2                                      NaN
3       Mrs. Jacques Heath (Lily May Peel)
4                        Mr. William Henry
                      ...
886                            Rev. Juozas
887                    Miss Margaret Edith
888          Miss Catherine Helen "Carrie"
889                        Mr. Karl Howell
890                            Mr. Patrick
Name: Name_main, Length: 891, dtype: object

In [65]:
titanic["Name_main"].str.split(", ")

0                                        NaN
1                                        NaN
2                                        NaN
3      [ Mrs. Jacques Heath (Lily May Peel)]
4                       [ Mr. William Henry]
                       ...
886                           [ Rev. Juozas]
887                   [ Miss Margaret Edith]
888         [ Miss Catherine Helen "Carrie"]
889                       [ Mr. Karl Howell]
890                           [ Mr. Patrick]
Name: Name_main, Length: 891, dtype: object

In [66]:
titanic['Real_Name']=titanic['Name'].str.split(", ").str.get(0)
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Surname,Name_main,Real_Name
0,1,0,3,anonymous,male,22.0,1,0,A/5 21171,7.2500,NaN,S,anonymous,NaN,anonymous
1,2,1,1,anonymous,female,38.0,1,0,PC 17599,71.2833,C85,C,anonymous,NaN,anonymous
2,3,1,3,anonymous,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,anonymous,NaN,anonymous
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Futrelle,Mrs. Jacques Heath (Lily May Peel),Futrelle
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Allen,Mr. William Henry,Allen

In [67]:
titanic["Surname"]=titanic["Name"].str.split(",").str.get(1)
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Surname,Name_main,Real_Name
0,1,0,3,anonymous,male,22.0,1,0,A/5 21171,7.2500,NaN,S,NaN,NaN,anonymous
1,2,1,1,anonymous,female,38.0,1,0,PC 17599,71.2833,C85,C,NaN,NaN,anonymous
2,3,1,3,anonymous,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,NaN,NaN,anonymous
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Mrs. Jacques Heath (Lily May Peel),Mrs. Jacques Heath (Lily May Peel),Futrelle
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Mr. William Henry,Mr. William Henry,Allen

In [68]:
titanic['Saturation']=titanic['Name'].str.split(", ").str.get(0)
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Surname,Name_main,Real_Name,Saturation
0,1,0,3,anonymous,male,22.0,1,0,A/5 21171,7.2500,NaN,S,NaN,NaN,anonymous,anonymous
1,2,1,1,anonymous,female,38.0,1,0,PC 17599,71.2833,C85,C,NaN,NaN,anonymous,anonymous
2,3,1,3,anonymous,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,NaN,NaN,anonymous,anonymous
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Mrs. Jacques Heath (Lily May Peel),Mrs. Jacques Heath (Lily May Peel),Futrelle,Futrelle
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Mr. William Henry,Mr. William Henry,Allen,Allen

In [69]:
titanic['Name'].str.contains("Mr")

0      False
1      False
2      False
3       True
4       True
       ...
886    False
887    False
888    False
889     True
890     True
Name: Name, Length: 891, dtype: bool

In [70]:
titanic['Name'].str.contains("Mrs")

0      False
1      False
2      False
3       True
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: Name, Length: 891, dtype: bool

In [71]:
titanic['Name'].str.contains("Miss")

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887     True
888     True
889    False
890    False
Name: Name, Length: 891, dtype: bool

In [72]:
titanic['Name'].str.contains("Master")

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: Name, Length: 891, dtype: bool

In [73]:
titanic['Name'].str.contains("Dr")

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: Name, Length: 891, dtype: bool

In [74]:
titanic['Name'].str.contains("Rev")

0      False
1      False
2      False
3      False
4      False
       ...
886     True
887    False
888    False
889    False
890    False
Name: Name, Length: 891, dtype: bool

In [75]:
titanic['Name'].str.contains("Col")

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: Name, Length: 891, dtype: bool

In [76]:
titanic['Name'].str.contains("Major")

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: Name, Length: 891, dtype: bool

In [77]:
titanic[titanic["Name"].str.contains("Major")]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Surname,Name_main,Real_Name,Saturation
449,450,1,1,"Peuchen, Major. Arthur Godfrey",male,52.0,0,0,113786,30.50,C104,S,Major. Arthur Godfrey,Major. Arthur Godfrey,Peuchen,Peuchen
536,537,0,1,"Butt, Major. Archibald Willingham",male,45.0,0,0,113050,26.55,B38,S,Major. Archibald Willingham,Major. Archibald Willingham,Butt,Butt

In [78]:
titanic['Name'].str.len()

0       9
1       9
2       9
3      44
4      24
       ..
886    21
887    27
888    39
889    21
890    19
Name: Name, Length: 891, dtype: int64

In [79]:
titanic['Name'].str.len().idxmax()

307

In [80]:
titanic.loc[titanic['Name'].str.len().idxmax(), 'Name']

'Penasco y Castellana, Mrs. Victor de Satode (Maria Josefa Perez de Soto y Vallejo)'

In [81]:
titanic['Name'].str.extract('([A-Za-z]+)\.')

       0
0    NaN
1    NaN
2    NaN
3    Mrs
4     Mr
..   ...
886  Rev
887  NaN
888  NaN
889   Mr
890   Mr

[891 rows x 1 columns]

In [82]:
titanic.loc[titanic['Name'].str.len().idxmin(), 'Name']

'anonymous'

In [83]:
titanic['Sex_short']=titanic['Sex'].replace({'male':'M', 'female':'F'})
titanic['Sex_short']

0      M
1      F
2      F
3      F
4      M
      ..
886    M
887    F
888    F
889    M
890    M
Name: Sex_short, Length: 891, dtype: object

In [86]:
titanic['Sex_short']=titanic['Sex'].str.replace('female','F')
titanic['Sex_short']=titanic['Sex_short'].str.replace('male','M')

In [87]:
import numpy as np
titanic['Sex_short']=titanic['Sex'].map({'male': 'M', 'female': 'F'})
titanic['Sex_short']

0      M
1      F
2      F
3      F
4      M
      ..
886    M
887    F
888    F
889    M
890    M
Name: Sex_short, Length: 891, dtype: object

In [88]:
import numpy as np
df= pd.DataFrame(np.random.randn(10, 3),columns=list("abc"))
df [["a","c","b"]]

          a         c         b
0 -0.607058  0.718981 -1.068297
1 -1.361064 -0.720661  1.093024
2 -1.276780 -2.875533 -1.775101
3 -0.453719 -1.139120  0.851437
4 -0.114375 -0.250091  0.912601
5  0.000888  0.243722  0.355804
6 -0.089307  0.406429 -0.836362
7  0.203799  0.116160  1.377444
8  0.139687 -0.898633 -0.550328
9  0.899205  0.028140 -0.676262

In [89]:
df.loc[:,["a","c"]]

          a         c
0 -0.607058  0.718981
1 -1.361064 -0.720661
2 -1.276780 -2.875533
3 -0.453719 -1.139120
4 -0.114375 -0.250091
5  0.000888  0.243722
6 -0.089307  0.406429
7  0.203799  0.116160
8  0.139687 -0.898633
9  0.899205  0.028140

In [91]:
named=list("abcdefghij")
n=30
columns=named+np.arange(len(named),n).tolist()
df=pd.DataFrame(np.random.randn(n,len(columns)),columns=columns)
df.head()

,a,b,c,d,e,f,g,h,i,j,...,20,21,22,23,24,25,26,27,28,29
0,-0.730944,1.278516,-0.572522,-0.041587,-0.085361,2.003053,-0.071176,-0.609784,-0.362389,-0.471738,...,1.364421,-1.596985,-0.255050,-0.254143,0.785787,0.602296,1.242943,-0.316779,1.120920,-0.438442
1,0.031402,1.206145,-0.867426,-0.124289,-0.686608,-0.530197,0.044375,-1.595200,0.541186,0.251857,...,-1.729668,-1.042232,0.087098,0.477953,-0.150370,-1.739980,-0.371426,-1.777877,-0.133271,-1.394802
2,-0.092374,0.877567,0.671812,-0.139750,0.253143,-0.818731,1.339308,0.973768,0.223674,0.016119,...,0.775615,1.025030,1.864850,1.213658,-0.266071,1.319011,1.576192,-0.023609,-1.451304,-0.172572
3,0.890000,-0.797352,0.591412,-1.150304,-0.681606,1.506979,0.386852,-0.865066,0.374758,-0.873406,...,-0.013814,0.014823,-0.493500,-1.686098,-1.575246,-1.283984,-1.111171,-0.111311,0.392618,0.305763
4,3.367319,1.336501,-0.353487,-0.475763,-0.451672,-0.364410,-0.729040,0.049810,-1.244060,-1.096785,...,-0.699790,-0.232554,-0.326303,-0.355682,0.290580,-0.836282,-0.833777,2.257420,-1.195021,-0.041563

In [92]:
named=list("abcdefghij")
n=30
columns=named+np.arange(len(named),n).tolist()
df=pd.DataFrame(np.random.randn(n,n),columns=columns)
df.iloc[:, np.r_[:10,24:30]]

,a,b,c,d,e,f,g,h,i,j,24,25,26,27,28,29
0,0.124149,-0.601230,-1.726750,-0.923688,-1.138428,1.843368,-0.384872,-0.021787,-0.471522,-1.191360,1.590282,-0.529238,-2.148615,-1.103005,-0.686242,0.248830
1,1.025482,0.620684,-0.702924,0.495550,0.216360,0.879805,0.183777,-0.104587,0.757124,-2.778825,1.635792,0.742345,-0.952541,-0.531178,-0.692741,0.352244
2,-0.845825,-1.022156,0.255415,-0.222762,-0.247898,1.934268,1.600198,2.890438,0.123550,-1.055808,0.421916,0.619897,0.971837,-0.944852,0.505165,-0.763170
3,0.524326,0.535444,-0.339184,-1.060910,1.541311,1.246931,-0.198429,1.080140,0.730242,1.107468,0.355787,1.186986,-0.992922,-2.945234,0.231428,-0.653575
4,0.967414,-1.544621,-0.867719,-0.571886,0.703994,-1.353290,1.242842,-0.259674,1.044038,0.043221,-0.044614,1.250870,-0.409653,0.210935,-0.099140,0.219004
5,-0.775674,0.660693,0.092748,0.614967,-0.976974,-0.758256,0.330829,0.442909,-0.195868,-0.064185,-0.647005,1.215621,-0.178919,-0.250179,-1.866527,0.701327
6,-0.167495,0.051374,1.024937,1.520298,0.598994,-0.852864,0.347701,0.804340,0.766902,-0.942944,-1.592257,-1.206606,-0.769269,0.525251,-0.683487,0.149458
7,0.506910,1.040977,0.908164,-0.062936,0.841059,-0.297540,-0.519556,1.147013,0.887128,1.461109,0.307541,-0.057590,0.087011,-0.038945,-2.213952,0.956270
8,-2.650819,-1.217792,0.439871,0.117216,-0.604953,1.242349,-0.321646,-0.927698,-1.729313,-1.245526,0.019561,0.483081,-0.365843,-0.903605,-1.761055,0.477372
9,-0.522034,-0.743235,1.842679,1.757405,-0.255120,0.264479,0.990297,-0.045296,-0.610210,-0.019364,-0.959716,-0.612297,1.497997,-0.695331,-0.179337,2.141647
10,-0.107981,-0.279033,0.666619,-1.802683,-0.985860,1.001826,0.692191,-1.286666,-0.478205,1.330519,-0.934492,1.435206,1.571522,-1.302622,-0.489920,0.706179
11,0.068927,-0.755223,-1.044300,1.309007,-0.220366,-0.660593,-0.650779,-1.329817,-0.934387,-2.388313,-0.042142,-0.147454,0.129262,0.411681,2.308326,1.563358
12,0.623479,-0.316836,-0.094676,-1.417683,0.697542,-0.394623,-0.920532,-0.825920,-1.055087,0.342211,0.078203,0.775201,-1.018828,0.597617,0.672821,-0.280750
13,1.079434,0.186111,0.474621,1.093663,-0.740472,-0.259177,0.511029,1.234615,0.847664,1.639642,0.304183,-1.878928,-0.326728,-1.488790,-0.505145,1.102338
14,1.381329,-1.009611,-2.791758,-0.538680,0.328434,-0.828432,2.239125,0.096472,0.445745,-1.475114,-1.987999,1.849393,-0.350936,0.725685,0.599907,-0.287392
15,-0.742563,-0.814597,0.350951,0.866032,0.657984,1.081406,0.602811,0.748267,0.345731,-0.070639,-0.046165,0.056014,1.262294,1.070166,-0.515459,-0.412375
16,0.966349,-0.875363,0.790381,-1.910964,0.913451,-0.886876,0.012520,1.328869,-0.825415,-0.101244,0.606795,-2.077233,-0.634725,0.560558,0.346151,-0.826187
17,0.255756,0.029341,-0.567750,0.242451,-1.117651,-0.436895,1.088097,0.313621,0.037319,-1.625982,-1.614697,2.415152,1.046560,0.140104,1.605571,0.561255
18,-0.798806,-0.247203,-0.266689,0.786998,-1.685963,0.803563,0.389480,-0.469848,-0.002498,1.176992,-1.024566,-0.740538,-2.115925,-0.670579,-0.027583,-2.264092
19,1.099134,-0.782941,0.321000,-0.357263,-0.291719,0.103895,-0.885898,0.730322,-0.942616,-0.322675,0.438584,0.499171,-0.471232,0.564653,0.906353,-1.959523
20,-0.788119,1.521422,2.044926,0.949637,1.827720,-1.092252,0.586056,-0.828029,1.384875,-0.440460,0.339646,-1.291687,0.564910,-0.562586,1.790630,1.496236
21,-0.733490,0.792751,0.175852,0.575509,-0.209681,-0.102750,0.301464,-2.793524,0.149114,0.352547,-0.425768,-0.842212,0.171407,-0.261694,0.934371,-0.224416
22,-0.126947,-0.600962,0.619916,0.521796,1.306107,2.640633,-1.537037,-1.094428,0.974345,2.387616,-0.797302,-1.371924,-0.214113,0.098184,-0.007707,0.698826
23,-0.910362,-2.034883,-0.109213,-0.648448,-0.739494,1.315765,-1.278134,-1.078616,0.373030,-0.258909,0.447838,-0.638404,-0.792850,0.902680,-0.532417,1.729305
24,1.306725,-0.714689,-0.811547,-2.285468,-0.107475,-0.401107,-1.439812,-0.048930,0.736934,0.382700,-0.279771,-1.909507,-0.215300,0.363330,0.555087,-0.631021
25,1.439214,0.344039,-0.775853,-0.122451,0.258024,1.205984,0.630736,-0.825896,2.049594,0.876030,-0.415445,1.013939,1.519848,-2.046973,0.379090,0.206817
26,-0.323995,0.141159,0.080102,-0.793831,-0.173898,-0.202309,0.387007,0.011744,-1.483868,-0.242862,-0.427992,-0.043610,0.075548,0.936024,0.756604,-1.703282
27,-0.799439,0.987678,-0.104334,-0.332773,0.852264,1.202546,-0.712440,-1.347466,0.266640,0.541930,-1.444895,-0.310790,-1.781323,-0.163557,1.457603,0.613012
28,-1.037601,-0.306508,-1.005407,1.934201,0.561733,0.148613,-0.693650,-0.744980,0.214877,0.223686,-0.346873,0.575202,-0.003788,1.087243,-1.210173,-1.195955
29,0.629363,-0.251441,0.464132,-0.268922,-0.335612,-0.026363,0.337355,-0.366867,-0.277787,0.414307,0.406495,-1.358839,-0.671838,-0.092301,0.174509,1.735052

In [95]:
df=pd.DataFrame({

"V1": [1, 3, 5, 7, 8, 3, 5, np.nan, 4, 5, 7, 9],
 "v2": [11, 33, 55, 77, 88, 33, 55, np.nan, 44, 55, 77, 99],
 "byl": ["red", "blue", 1, 2, np.nan, "big", 1, 2, "red", 1, np.nan, 12],
 "by2": ["wet", "dry", 99, 95, np. nan, "damp", 95, 99, "red", 99, np. nan, np.nan, ]


})
df

     V1    v2   byl   by2
0   1.0  11.0   red   wet
1   3.0  33.0  blue   dry
2   5.0  55.0     1    99
3   7.0  77.0     2    95
4   8.0  88.0   NaN   NaN
5   3.0  33.0   big  damp
6   5.0  55.0     1    95
7   NaN   NaN     2    99
8   4.0  44.0   red   red
9   5.0  55.0     1    99
10  7.0  77.0   NaN   NaN
11  9.0  99.0    12   NaN

In [99]:
g=df.groupby(["byl","by2"])
g[["V1","v2"]].mean()

            V1    v2
byl  by2
1    95    5.0  55.0
     99    5.0  55.0
2    95    7.0  77.0
     99    NaN   NaN
big  damp  3.0  33.0
blue dry   3.0  33.0
red  red   4.0  44.0
     wet   1.0  11.0

In [103]:
import numpy as np
s=pd.Series(np.arange(5),dtype=np.float32)
s

0    0.0
1    1.0
2    2.0
3    3.0
4    4.0
dtype: float32

In [104]:
s.isin([2,4])

0    False
1    False
2     True
3    False
4     True
dtype: bool

In [107]:
import random

import string

baseball=pd. DataFrame({

"team": ["team %d" % (x + 1) for x in range(5)]* 5,

"player": random.sample(list(string.ascii_lowercase), 25),

"batting avg": np.random.uniform(0.200, 0.400, 25),

}

)

baseball

      team player  batting avg
0   team 1      k     0.380991
1   team 2      u     0.386419
2   team 3      v     0.279884
3   team 4      f     0.244696
4   team 5      t     0.236529
5   team 1      m     0.254363
6   team 2      s     0.383934
7   team 3      o     0.274294
8   team 4      i     0.214183
9   team 5      w     0.328801
10  team 1      h     0.284888
11  team 2      x     0.362293
12  team 3      z     0.286049
13  team 4      d     0.261528
14  team 5      r     0.268968
15  team 1      j     0.308053
16  team 2      p     0.207542
17  team 3      e     0.259460
18  team 4      c     0.250813
19  team 5      a     0.332555
20  team 1      y     0.391794
21  team 2      l     0.216410
22  team 3      q     0.203423
23  team 4      b     0.265640
24  team 5      g     0.335519

In [108]:
baseball.pivot_table(values="batting avg", index="team", columns="player")

player,a,b,c,d,e,f,g,h,i,j,...,q,r,s,t,u,v,w,x,y,z
team,,,,,,,,,,,,,,,,,,,,,
team 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.284888,NaN,0.308053,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.391794,NaN
team 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.383934,NaN,0.386419,NaN,NaN,0.362293,NaN,NaN
team 3,NaN,NaN,NaN,NaN,0.25946,NaN,NaN,NaN,NaN,NaN,...,0.203423,NaN,NaN,NaN,NaN,0.279884,NaN,NaN,NaN,0.286049
team 4,NaN,0.26564,0.250813,0.261528,NaN,0.244696,NaN,NaN,0.214183,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
team 5,0.332555,NaN,NaN,NaN,NaN,NaN,0.335519,NaN,NaN,NaN,...,NaN,0.268968,NaN,0.236529,NaN,NaN,0.328801,NaN,NaN,NaN

In [109]:
df=pd.DataFrame({"a":np.random.randn(1000), "b":np.random.randn(1000), "c":np.random.randn(1000)})
df.head()

          a         b         c
0  1.057421 -2.510817 -0.572445
1 -1.148319  0.444310  1.810796
2  0.079181 -2.026404  0.844532
3 -0.115616 -0.035169 -0.101722
4  0.569977  1.806611 -0.553447

In [110]:
df.query("a < b")

            a         b         c
1   -1.148319  0.444310  1.810796
3   -0.115616 -0.035169 -0.101722
4    0.569977  1.806611 -0.553447
9   -0.222732  0.142543  1.107663
13  -0.220078  0.685176 -1.393180
..        ...       ...       ...
994 -1.294719  2.038559 -0.505128
995  0.116114  0.795359 -0.401917
996 -1.105803 -0.765629  0.057449
998 -1.263522  0.514341 -0.179215
999  0.203606  0.565472  0.646821

[468 rows x 3 columns]

In [111]:
df[df["a"]<df["b"]]

            a         b         c
1   -1.148319  0.444310  1.810796
3   -0.115616 -0.035169 -0.101722
4    0.569977  1.806611 -0.553447
9   -0.222732  0.142543  1.107663
13  -0.220078  0.685176 -1.393180
..        ...       ...       ...
994 -1.294719  2.038559 -0.505128
995  0.116114  0.795359 -0.401917
996 -1.105803 -0.765629  0.057449
998 -1.263522  0.514341 -0.179215
999  0.203606  0.565472  0.646821

[468 rows x 3 columns]

In [113]:
df.loc[df["a"]<df["b"]]

            a         b         c
1   -1.148319  0.444310  1.810796
3   -0.115616 -0.035169 -0.101722
4    0.569977  1.806611 -0.553447
9   -0.222732  0.142543  1.107663
13  -0.220078  0.685176 -1.393180
..        ...       ...       ...
994 -1.294719  2.038559 -0.505128
995  0.116114  0.795359 -0.401917
996 -1.105803 -0.765629  0.057449
998 -1.263522  0.514341 -0.179215
999  0.203606  0.565472  0.646821

[468 rows x 3 columns]

In [114]:
df[df["a"]>=df["b"]]

            a         b         c
0    1.057421 -2.510817 -0.572445
2    0.079181 -2.026404  0.844532
5   -0.179583 -1.180030 -1.159348
6   -0.181987 -0.701051  0.699586
7    1.057423 -0.835692  0.380028
..        ...       ...       ...
989  1.519461  0.834779 -1.629828
991  1.016889 -1.563450  1.223799
992  0.553670 -0.448505 -2.192985
993 -0.603399 -2.273739  2.610017
997  1.249584  0.666183  0.312297

[532 rows x 3 columns]

In [115]:
df=pd.DataFrame({"a":np.random.randn(1000), "b":np.random.randn(1000), "c":np.random.randn(1000)})
df.head()

          a         b         c
0  0.972605 -1.799641  0.339671
1  1.930955 -0.922051 -1.577336
2  0.912083 -0.033138  0.069711
3 -0.622792 -1.120913  0.338382
4  0.755190  0.416179  0.872794

In [116]:
df.eval("a+b+c")

0     -0.487365
1     -0.568432
2      0.948656
3     -1.405322
4      2.044164
         ...
995    0.534646
996    1.639316
997   -1.275792
998   -2.444059
999    0.433778
Length: 1000, dtype: float64

In [117]:
df["a"]+df["b"]+df["c"]

0     -0.487365
1     -0.568432
2      0.948656
3     -1.405322
4      2.044164
         ...
995    0.534646
996    1.639316
997   -1.275792
998   -2.444059
999    0.433778
Length: 1000, dtype: float64

In [119]:
df=pd.DataFrame({

"x": np.random.uniform (1.8, 168.0, 120),

"y": np.random.uniform (7.0, 334.0, 120),

"z": np.random.uniform(1.7, 20.7, 120),

"month": [5, 6, 7, 8]* 30,

"week": np.random.randint(1, 4, 120)

})

df.head()

            x           y          z  month  week
0   46.488714  316.631131  11.979918      5     2
1  144.266018  133.114268  17.851537      6     3
2   15.161645   60.623504  17.241611      7     3
3    4.436462  303.229011  15.899860      8     2
4  104.795645  243.772710  18.752011      5     3

In [120]:
grouped=df.groupby(["month","week"])
grouped["x"].agg(np.mean)

<ipython-input-120-9d948f7290fd>:2: FutureWarning: The provided callable <function mean at 0x79f67b7f55a0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  grouped["x"].agg(np.mean)

month  week
5      1        89.253880
       2        86.872417
       3        90.828829
6      1       100.224144
       2        94.914863
       3       100.800948
7      1        79.691571
       2        84.553963
       3        87.496428
8      1        56.486153
       2        77.457709
       3       120.568148
Name: x, dtype: float64

In [121]:
a=np.array(list(range(1,24))+[np.NAN]).reshape(2,3,4)
a

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]],

       [[13., 14., 15., 16.],
        [17., 18., 19., 20.],
        [21., 22., 23., nan]]])

In [122]:
pd.DataFrame([tuple(list(x)+[val]) for x , val in np.ndenumerate(a)])

    0  1  2     3
0   0  0  0   1.0
1   0  0  1   2.0
2   0  0  2   3.0
3   0  0  3   4.0
4   0  1  0   5.0
5   0  1  1   6.0
6   0  1  2   7.0
7   0  1  3   8.0
8   0  2  0   9.0
9   0  2  1  10.0
10  0  2  2  11.0
11  0  2  3  12.0
12  1  0  0  13.0
13  1  0  1  14.0
14  1  0  2  15.0
15  1  0  3  16.0
16  1  1  0  17.0
17  1  1  1  18.0
18  1  1  2  19.0
19  1  1  3  20.0
20  1  2  0  21.0
21  1  2  1  22.0
22  1  2  2  23.0
23  1  2  3   NaN

In [124]:
a=list(enumerate(list(range(1,5))+[np.NAN]))
a

[(0, 1), (1, 2), (2, 3), (3, 4), (4, nan)]

In [125]:
pd.DataFrame(a)

   0    1
0  0  1.0
1  1  2.0
2  2  3.0
3  3  4.0
4  4  NaN

In [126]:
cheese=pd.DataFrame({


"first": ["John", "Mary"],

"last": ["Doe", "Bo"],

"height": [5.5, 6.0],

"weight": [130, 150]

})

cheese

  first last  height  weight
0  John  Doe     5.5     130
1  Mary   Bo     6.0     150

In [127]:
pd.melt(cheese, id_vars=["first", "last"])

  first last variable  value
0  John  Doe   height    5.5
1  Mary   Bo   height    6.0
2  John  Doe   weight  130.0
3  Mary   Bo   weight  150.0

In [128]:
cheese.set_index(["first", "last"], inplace=True)
cheese

            height  weight
first last
John  Doe      5.5     130
Mary  Bo       6.0     150

In [131]:
cheese.stack() # Since 'first' and 'last' are already the index, simply use stack()

first  last
John   Doe   height      5.5
             weight    130.0
Mary   Bo    height      6.0
             weight    150.0
dtype: float64

In [133]:
 df=pd.DataFrame({

"x": np.random.uniform(1.0, 168.0, 12),

"y": np.random.uniform (7.0, 334.0, 12),

"z": np.random.uniform (1.7, 20.7, 12),

"month": [5, 6, 7]* 4,

"week": [1, 2]* 6

})

df=pd.DataFrame({

"x": np.random.uniform(1.0, 168.0, 12),

"y": np.random.uniform (7.0, 334.0, 12),

"z": np.random.uniform (1.7, 20.7, 12),

"month": [5, 6, 7]* 4,

"week": [1, 2]* 6

})

mdf=pd.melt(df, id_vars=["month", "week"])

pd.pivot_table(mdf, values="value", index=["variable", "week"], columns=["month"])

month                   5           6           7
variable week
x        1     140.024465   65.604546   77.464744
         2      39.967018  109.847007  101.728212
y        1     186.442311   20.973490  105.989513
         2     285.159927  234.732918   91.711548
z        1       9.584910   12.791087    9.383584
         2       9.377580   10.194410    6.859898

In [140]:
import pandas as pd
df=pd.DataFrame({
"Animal": ["Animall", "Animal2", "Animal3", "Animal2", "Animall", "Animal2", "Animal3"],
"FeedType": ["A", "B", "A", "A", "B", "B", "A"],
"Amount": [10, 7, 4, 2, 5, 6, 21]
})

df.pivot_table(values="Amount", index="Animal", columns="FeedType", aggfunc="sum")

FeedType     A     B
Animal
Animal2    2.0  13.0
Animal3   25.0   NaN
Animall   10.0   5.0

In [141]:
df.groupby(["Animal", "FeedType"])["Amount"].sum()

Animal   FeedType
Animal2  A            2
         B           13
Animal3  A           25
Animall  A           10
         B            5
Name: Amount, dtype: int64

In [142]:
pd.cut(pd.Series(np.arange(10)), 5)

0    (-0.009, 1.8]
1    (-0.009, 1.8]
2       (1.8, 3.6]
3       (1.8, 3.6]
4       (3.6, 5.4]
5       (3.6, 5.4]
6       (5.4, 7.2]
7       (5.4, 7.2]
8       (7.2, 9.0]
9       (7.2, 9.0]
dtype: category
Categories (5, interval[float64, right]): [(-0.009, 1.8] < (1.8, 3.6] < (3.6, 5.4] < (5.4, 7.2] <
                                           (7.2, 9.0]]

In [143]:
pd.Series([1,2,3,4,5,6,7,8,9,10]).rolling(3).sum()

0     NaN
1     NaN
2     6.0
3     9.0
4    12.0
5    15.0
6    18.0
7    21.0
8    24.0
9    27.0
dtype: float64

In [144]:
pd.Series([1,2,3,4,5,6,7,8,9,10]).rolling(3).mean()

0    NaN
1    NaN
2    2.0
3    3.0
4    4.0
5    5.0
6    6.0
7    7.0
8    8.0
9    9.0
dtype: float64

In [145]:
pd.Series([1,2,3,4,5,6,7,8,9,10]).rolling(3).median()

0    NaN
1    NaN
2    2.0
3    3.0
4    4.0
5    5.0
6    6.0
7    7.0
8    8.0
9    9.0
dtype: float64

In [146]:
pd.Series([1,2,3,2,2,3]).astype("category")

0    1
1    2
2    3
3    2
4    2
5    3
dtype: category
Categories (3, int64): [1, 2, 3]

In [148]:
frame=pd.DataFrame({"col1":list({"A","B","C"}),"col2":list({"A","B","C"})})
frame

  col1 col2
0    A    A
1    B    B
2    C    C

In [149]:
frame[frame["col1"].isna()]

Empty DataFrame
Columns: [col1, col2]
Index: []

In [150]:
frame[frame["col1"].notna()]

  col1 col2
0    A    A
1    B    B
2    C    C

In [151]:
df1=pd.DataFrame({"col1":list({"A","B","C"}),"col2":list({"A","B","C"})})
df2=pd.DataFrame({"col1":list({"A","B","C"}),"col2":list({"A","B","C"})})

In [153]:
pd.concat([df1,df2])

  col1 col2
0    A    A
1    B    B
2    C    C
0    A    A
1    B    B
2    C    C

In [154]:
indexed_df2=df2.set_index("col1")
pd.merge(df1,indexed_df2,left_on="col1",right_index=True)

  col1 col2_x col2_y
0    A      A      A
1    B      B      B
2    C      C      C

In [156]:
pd.merge(df1,df2,on="col1",how="left")

  col1 col2_x col2_y
0    A      A      A
1    B      B      B
2    C      C      C

In [157]:
pd.merge(df1,df2,on="col1",how="right")

  col1 col2_x col2_y
0    A      A      A
1    B      B      B
2    C      C      C

In [158]:
pd.merge(df1,df2,on="col1",how="outer")

  col1 col2_x col2_y
0    A      A      A
1    B      B      B
2    C      C      C

In [ ]:
df=pd.DataFrame({"col1":list({"A","B","C"}),"col2":list({"A","B","C"})})
df